- src/containers/orgs/OrgContainer.js
- src/containers/orgs/OrgsContainer.js
- src/containers/orgs/OrgsReducer.js
- src/core/redux/ReduxActions.js
- src/core/router/Routes.js
> super basic org details page

- package.json
- src/containers/orgs/OrgContainer.js
- src/containers/orgs/OrgsReducer.js
- src/containers/orgs/components/DeleteOrgModal.js
- src/core/redux/ReduxStore.js
- src/core/sagas/Sagas.js
> delete org modal

- package.json
- src/containers/orgs/OrgContainer.js
- src/containers/orgs/OrgsContainer.js
- src/containers/orgs/OrgsReducer.js
- src/containers/orgs/OrgsSagas.js
- src/core/sagas/Sagas.js
> integration account details

- src/index.html
- src/index.js
> Inter font!

- package.json
- src/containers/orgs/OrgsContainer.js
- src/containers/orgs/OrgsReducer.js
- src/containers/orgs/components/OrgDescriptionSection.js
- src/containers/orgs/components/OrgMembersSection.js
- src/containers/orgs/components/OrgTitleSection.js
- src/core/redux/ReduxActions.js
- src/core/sagas/Sagas.js
- src/utils/ValidationUtils.js
- src/utils/index.js
create org button
create org modal
create org pending
create org failure
> create new organization

- src/containers/orgs/OrgPermissionsContainer.js
- src/containers/orgs/OrgsReducer.js
- src/containers/orgs/OrgsSagas.js
- src/containers/orgs/index.js
Prior to this fix, the page would break if the user clicks on a role. Now, it shows an error message.
> show unauthorized error for role permissions

- package.json
> fix(package): update luxon to version 1.21.0

- package.json
> fix(package): update lattice-sagas to version 0.47.0

- package.json
> fix(package): update lattice to version 0.70.1

- package.json
> fix(package): update lattice-fabricate to version 0.12.1

- package.json
> fix(package): update lattice-ui-kit to version 0.30.1

- package.json
> chore(package): update html-webpack-plugin to version 4.2.0

- src/containers/orgs/components/OrgRoleGrantsSection.js
- duplicate GrantTypes in the select
- missing data in the table
> fix the role grants section

- src/containers/orgs/OrgRolesContainer.js
see screenshot: https://jira.openlattice.com/browse/APPS-2113
> a fix for the WTF bug

- src/components/grids/StackGrid.js
- src/containers/org/OrgContainer.js
- src/containers/org/OrgRouter.js
- src/containers/org/components/DataSetPermissionsCard.js
- src/containers/org/components/DataSetPermissionsContainer.js
- src/containers/org/components/PermissionsPanel.js
- src/containers/org/components/index.js
- src/containers/org/members/MembersSection.js
- src/containers/org/members/OrgMemberContainer.js
- src/containers/org/members/OrgMembersContainer.js
- src/containers/org/members/index.js
- src/containers/org/roles/OrgRoleContainer.js
- src/containers/org/sagas/initializeOrganization.js
- src/core/permissions/actions/index.js
- src/core/permissions/reducers/getEntitySetPermissionsReducer.js
- src/core/permissions/reducers/getPropertyTypePermissionsReducer.js
- src/core/permissions/reducers/index.js
- src/core/permissions/sagas/getEntitySetPermissions.js
- src/core/permissions/sagas/index.js
- src/core/sagas/Sagas.js
- src/types.js
- src/utils/PersonUtils.js
- src/utils/constants/index.js
- src/utils/getPrincipal.js
- src/utils/index.js
> OrgMemberContainer

- package-lock.json
- package.json
- src/containers/org/DataSetPermissionsCard.js
- src/containers/org/DataSetPermissionsContainer.js
- src/containers/org/components/DataSetPermissionsCard.js
- src/containers/org/components/PermissionsPanel.js
- src/containers/org/components/SearchDataSetsForm.js
- src/containers/org/components/index.js
- src/containers/org/members/OrgMemberContainer.js
- src/containers/org/roles/OrgRoleContainer.js
- src/core/edm/reducers/index.js
- src/core/edm/reducers/searchEntitySetMetaDataReducer.js
- src/core/permissions/sagas/getDataSetPermissions.js
- src/core/redux/ReduxReducer.js
- src/core/redux/ReduxStore.js
- src/core/redux/constants/index.js
- src/core/redux/selectors/index.js
- src/core/redux/selectors/selectDataSetSearchHits.js
- src/core/sagas/Sagas.js
- src/core/search/actions/index.js
- src/core/search/actions/index.test.js
- src/core/search/constants/index.js
- src/core/search/index.js
- src/core/search/reducers/clearSearchStateReducer.js
- src/core/search/reducers/index.js
- src/core/search/reducers/searchDataSetsReducer.js
- src/core/search/sagas/index.js
- src/core/search/sagas/searchDataSets.js
- src/types.js
- src/utils/testing/TestUtils.js
Adding search to `DataSetPermissionsContainer`.
> data set permissions filters

- src/components/other/Divider.js
- src/containers/org/components/PermissionsPanel.js
> add a checkbox for the data set permission

- src/containers/org/components/DataSetSearchResultCard.js
> use an icon to differentiate entity sets vs atlas data sets

- src/containers/org/DataSetPermissionsContainer.js
- src/containers/org/DataSetPermissionsModal.js
- src/core/search/constants/index.js
- src/core/search/reducers/clearSearchStateReducer.js
- src/core/search/reducers/index.js
- src/core/search/reducers/searchDataSetsReducer.js
- src/core/search/reducers/searchDataSetsToAssignPermissionsReducer.js
- src/core/search/reducers/searchDataSetsToFilterReducer.js
- src/core/search/sagas/searchDataSets.js
> it seems to be working ok, needs more polish

- src/components/buttons/CopyButton.js
- src/containers/org/OrgContainer.js
- src/containers/org/OrgRouter.js
- src/containers/org/settings/OrgSettingsContainer.js
> add link to settings

- package-lock.json
- package.json
- src/components/grids/StackGrid.js
- src/components/other/Divider.js
- src/components/other/Pre.js
- src/components/other/index.js
- src/containers/account/AccountContainer.js
- src/containers/account/actions/index.js
- src/containers/account/index.js
- src/containers/account/reducers/clearAtlasCredentialsReducer.js
- src/containers/account/reducers/getAtlasCredentialsReducer.js
- src/containers/account/reducers/index.js
- src/containers/app/AppContainer.js
- src/containers/org/settings/OrgSettingsContainer.js
- src/core/redux/ReduxReducer.js
- src/core/redux/constants/index.js
- src/core/redux/selectors/index.js
- src/core/redux/selectors/selectAtlasCredentials.js
- src/core/router/Routes.js
- src/core/sagas/Sagas.js
- src/utils/clipboardWriteText.js
- src/utils/index.js
Depends on:
https://github.com/openlattice/lattice-js/pull/1069
https://github.com/openlattice/lattice-sagas/pull/673
> new account page

- src/containers/org/OrgDataSetContainer.js
- src/containers/org/OrgDataSetsContainer.js
- src/containers/org/OrgObjectPermissionsContainer.js
- src/containers/org/OrgRoleContainer.js
- src/containers/org/OrgRoleObjectPermissionsContainer.js
- src/containers/org/OrgRolesContainer.js
- src/containers/org/OrgRouter.js
- src/containers/org/components/RoleActionButton.js
- src/containers/org/members/OrgMemberContainer.js
- src/containers/org/members/OrgMembersContainer.js
- src/containers/org/settings/OrgSettingsContainer.js
- src/utils/stateReducers/pagination.js
> org roles page

- src/containers/org/OrgContainer.js
- src/containers/org/actions/index.js
- src/containers/org/components/DeleteOrgModal.js
- src/containers/org/components/OrgActionButton.js
- src/containers/org/reducers/deleteExistingOrganizationReducer.js
- src/containers/org/reducers/index.js
- src/containers/org/sagas/deleteExistingOrganization.js
- src/containers/org/sagas/index.js
- src/containers/orgs/OrgsReducer.js
- src/core/sagas/Sagas.js
> Task/APPS-2750 — delete organization

- src/components/buttons/index.js
- src/components/other/Flip.js
- src/components/other/index.js
- src/containers/org/OrgContainer.js
- src/core/edm/constants/index.js
- src/core/search/sagas/searchOrganizationDataSets.js
> EntitySetFlagTypes search option

- src/containers/org/OrgDataSetContainer.js
> show data set schema

- .github/CODEOWNERS
- src/containers/org/utils/generateIntegrationConfig.js
This PR:
-Updates the integration config template
> update integration configuration generator

- src/containers/org/components/RemoveMemberFromOrgModal.js
- src/containers/org/people/PeopleTable.js
- src/containers/org/people/components/TableRow.js
> you should be able to leave an organization

- src/components/other/NavContentWrapper.js
- src/components/other/SearchForm.js
- src/containers/org/OrgDataSetContainer.js
- src/core/router/Routes.js
- Updated styles on nav tabs
- Added text 'Search' to search button.
> APPS-2914  & APPS-2915 Search UI Updates

- src/containers/org/OrgDataSetContainer.js
- src/core/edm/actions/index.js
- src/core/edm/reducers/getOrgDataSetSizeReducer.js
- src/core/edm/reducers/index.js
- src/core/edm/sagas/getOrgDataSetSize.js
- src/core/edm/sagas/index.js
- src/core/redux/constants/index.js
- src/core/redux/selectors/index.js
- src/core/redux/selectors/selectOrgDataSetSize.js
- src/core/sagas/Sagas.js
- adds `getOrgDataSetSize` Action, Saga, Reducer
- adds Badges to `OrgDataSetContainer` for 'Fields' and 'Records' counts
> APPS-2901: Add fields and records count

- src/containers/explore/EntityNeighborsContainer.js
> Remove Association Chips

- src/containers/org/OrgDataSetContainer.js
- src/core/redux/selectors/index.js
- src/core/redux/selectors/selectEntityType.js
- src/utils/constants/index.js
> Add Entity Type to Data Set Container
